language: node_js
node_js:
  - 6
  - 8
  - 'stable'

script:
  - npm run lint
  - npm run test

notifications:
  email:
    recipients:
      - adam@apiary.io
    on_success: change
    on_failure: always
